FROM openjdk:17

USER root

ENV ARTIFACT_NAME=exam3-0.0.1-SNAPSHOT
ENV ARTIFACT_PATH=/build/libs
ENV PORT=8080
ENV APP_HOME=/opt/app
ENV ARTIFACT=${ARTIFACT_NAME}.jar

RUN mkdir -p /opt/app
COPY --chown=1001:0 ${ARTIFACT_PATH}/${ARTIFACT} ${APP_HOME}/${ARTIFACT}

WORKDIR ${APP_HOME}
EXPOSE ${PORT}

ENTRYPOINT java ${JAVA_OPTS} -jar ${ARTIFACT}
